# Generated by Django 4.1.10 on 2023-08-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciperadar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.JSONField()),
                ('instructions', models.TextField()),
                ('cuisine', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciperadar.userprofile')),
            ],
        ),
    ]
