# Generated by Django 4.1.10 on 2023-08-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciperadar', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciperadar.recipe')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciperadar.userprofile')),
            ],
        ),
    ]
