# Generated by Django 4.1.10 on 2023-08-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciperadar', '0003_savedrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciperadar.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciperadar.userprofile')),
            ],
        ),
    ]
