# Generated by Django 4.1.10 on 2023-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperadar', '0006_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True),
        ),
    ]
