# Generated by Django 4.1.10 on 2023-09-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperadar', '0007_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
